<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4048a228fa5a421e8582c9dbdc2fd7ac
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
        'C' => 
        array (
            'Composer\\Installers\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/Twilio',
        ),
        'Composer\\Installers\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4048a228fa5a421e8582c9dbdc2fd7ac::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4048a228fa5a421e8582c9dbdc2fd7ac::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
